public class StatusTransferIssue{

    public StatusTransferIssue(){
        //Empty constructor 
    }

    /* 
    * Fires a bug
    */
    public void bugFire(String param){
        param = 'fire bug';
    } 

        /* 
    * Fires a bug
    */
    public void bugFireAgain(String param){
        param = 'fire bug again';
    } 

    public void bugFireAgainAndAgain(String param){
        param = 'fire bug again and again';
    } 

}